posts/urls.py
from django.urls import path
from .views import (
    likeControl,
    index,
    loadData,
    likeControl,
    commentControl,
    postControl,
    editPost,
    deletePost,
    editSave,
)

app_name = 'posts'

urlpatterns = [
    path('', index, name='main'),
    path('data/', loadData, name='posts-data'),
    path('likeControl/', likeControl, name="likeControl"),
    path('editPost/', editPost, name='editPost'),
    path('editSave/', editSave, name='editSave'),
    path('deletePost/', deletePost, name='deletePost'),
    path('commentControl/', commentControl, name="commentControl"),
    path('postControl/', postControl, name="postControl")
]

social_site/urls.py
from django.contrib import admin
from django.urls import path,  include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout_then_login

from posts.views import editPost
from . import views

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.signup, name='signup'),
    
    path('login/', views.Login, name='login'),
    path('', include('posts.urls', namespace='post')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('userProfile/', views.userProfile, name='userProfile')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Profile
# Create your models here.


class Post(models.Model):
    def upload_to(instance, filename):
        return '%s/images/%s'% (instance.author.user.username, filename)

    content = models.TextField()
    liked = models.ManyToManyField(User, blank=True, related_name="liked")
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=upload_to, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content)    

    @property
    def likeCount(self):
        return self.liked.all().count()

class Comments(models.Model):
    comment = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    commenter = models.ForeignKey(Profile, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content', 'image')
        labels = {
            'content': "What's new?",
            'image': 'Upload a picture'
        }

class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content', 'image')
        labels = {
            'content': "What's new?",
            'image': 'Upload a picture'
        }

posts/views.py
from json.encoder import JSONEncoder
from django.shortcuts import render

from social_site.views import Login
from .models import Post, Profile, Comments
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .forms import PostForm, EditForm
from profiles.models import Profile
# Create your views here.


@login_required(login_url='login')
def index(request):
    form = PostForm
    editForm = EditForm(auto_id="edit_%s")
    return render(request, 'posts/main.html', {'form': form, 'editForm': editForm})

def editSave(request):
    if request.is_ajax():
        post = Post.objects.get(id=request.POST.get('pk'))
        postImage = request.FILES.get('postedImage')
        postContent = request.POST.get('postContent')
        if post.author.user == request.user:
            if postImage == None:
                if postContent != '':
                    post.content = postContent
                    post.image = postImage
                    post.save()
            else:
                post.content = postContent
                post.image = postImage
                post.save()
            return JsonResponse({})

def deletePost(request):
    if request.is_ajax():
        post = Post.objects.get(id=request.POST.get('pk'))
        if post.author.user == request.user:
            postJSON = {
                'id': post.id
            }
            post.delete()
            return JsonResponse({'post': postJSON})

def editPost(request):
    if request.is_ajax():
        post = Post.objects.get(id=request.POST.get('pk'))
        if post.author.user == request.user:
            if post.image:
                postImage = post.image.url
            else:
                postImage = ""
            postJSON = {
                'id': post.id,
                'author': post.author.id,
                'count': post.likeCount,
                'content': post.content,
                'postImage': postImage
            }
            
            return JsonResponse({'post': postJSON})
        else:
            return JsonResponse({'message':"DONT TOUCH, YOU DONT OWN THIS!"})

def postControl(request):
    if request.is_ajax():
        postImage = request.FILES.get('postedImage')
        postContent = request.POST.get('postContent')

        if postContent != '' or postImage != None:
            postCreator = Profile.objects.get(user=request.user)
            newPost = Post()
            newPost.image = postImage
            newPost.author = postCreator
            newPost.content = postContent
            newPost.save()
            if (postImage != None):
                postImageURL = newPost.image.url

            else:
                postImageURL = '/'
            newPostJSON = {
                'id': newPost.id,
                'author': newPost.author.id,
                'content': newPost.content,
                'count': newPost.likeCount,
                'postImage': postImageURL,
            }
            newPostAuthorJSON = {
                'name': postCreator.firstName + " " + postCreator.lastName,
                'profilePic': str(postCreator.profilePic.url),
                'firstName': postCreator.firstName,
                'lastName': postCreator.lastName
            }
            return JsonResponse({'post': newPostJSON, 'author': newPostAuthorJSON})


def loadData(request):
    currentUser = request.user
    currentUserProfile = Profile.objects.get(user=currentUser)
    currentUserFriends = currentUserProfile.friends.all()

    friendsJSON = []
    for frnd in currentUserFriends:
        friendOBJ = Profile.objects.get(id=frnd.id)
        friend = {
            'id': friendOBJ.id,
            'firstName': friendOBJ.firstName,
            'lastName': friendOBJ.lastName,
        }
        friendsJSON.append(friend)

    allComments = Comments.objects.all().order_by('-created')
    allCommentsListJSON = []
    for comment in allComments:
        com = {
            'id': comment.id,
            'comment': comment.comment,
            'post': comment.post.id,
            'commenter': comment.commenter.id,
            'name': comment.commenter.firstName + " " + comment.commenter.lastName,
            'profilePic': str(comment.commenter.profilePic.url)
        }
        allCommentsListJSON.append(com)

    allPosts = Post.objects.all().order_by('-created')
    allPostListJSON = []
    for post in allPosts:
        full_name = post.author.firstName + " " + post.author.lastName
        if (post.image):
            postImage = str(post.image.url)
        else:
            postImage = ''
        item = {
            'id': post.id,
            'content': post.content,
            'author': post.author.user.id,
            'authorFirstName': post.author.firstName,
            'authorLastName': post.author.lastName,
            'profilePic': str(post.author.profilePic.url),
            'liked': True if request.user in post.liked.all() else False,
            'count': post.likeCount,
            'name': full_name,
            'created': post.created,
            'postImage': postImage
        }
        allPostListJSON.append(item)
    currentUserProfileJSON = {
        'id': currentUserProfile.id,
        'firstName': currentUserProfile.firstName,
        'lastName': currentUserProfile.lastName,
        'profilePic': str(currentUserProfile.profilePic.url)
    }
    return JsonResponse({'currentUser': currentUserProfileJSON, 'allPosts': allPostListJSON, 'friends': friendsJSON, 'comments': allCommentsListJSON})


def likeControl(request):
    if request.is_ajax():
        pk = request.POST.get('pk')
        post = Post.objects.get(id=pk)
        if request.user in post.liked.all():
            liked = False
            post.liked.remove(request.user)
        else:
            liked = True
            post.liked.add(request.user)
        return JsonResponse({'liked': liked, 'count': post.likeCount})


def commentControl(request):
    if request.is_ajax():
        pk = request.POST.get('pk')
        allComments = Comments.objects.all().order_by('created')
        post = Post.objects.get(id=pk)
        comment = Comments()
        comment.post = post
        comment.commenter = Profile.objects.get(user=request.user)
        commenterFullName = comment.commenter.firstName + " " + comment.commenter.lastName
        comment.comment = request.POST.get('comment')
        commentList = []
        for comments in allComments:
            commentOBJ = Comments.objects.get(id=comments.id)
            com = {
                'id': commentOBJ.id,
                'comment': commentOBJ.comment,
                'post': commentOBJ.post.id,
                'commenter': commentOBJ.commenter.user.id,
                'profilePic': str(commentOBJ.commenter.profilePic.url)
            }
            commentList.append(com)
        if comment.comment != '':
            comment.save()
            return JsonResponse({'commentList': commentList, 'id': comment.id, 'comment': str(comment.comment), 'commenter': commenterFullName, 'profilePic': str(comment.commenter.profilePic.url)})

posts/templates/posts/main.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} {% block scripts %}
<script src="{% static 'posts/main.js' %}" defer></script>
{% endblock scripts %} {% block title %} | Posts {% endblock title %} {% block left %}
<div class="col-sm-12" style="
        height:250;
        max-height:500px;
        overflow:auto;
        margin-bottom:10px;
        box-shadow:3px 3px 2px gray;
        background:#ffffff;
        padding-left:5px;
        padding-top:10px;
        padding-bottom:10px;
        margin-top:10px;
        margin-left:10px;
        border:solid 1px black">
    <h3>NOTIFICATIONS</h3>
    Coming soon!<br><br>

    <strong>New Features in the works:</strong><br> 
    Profile page<br> 
    Edit name, profile pic, etc<br> 
    Edit/Remove posts<br> 
    Friend Control<br> 
    View Friends Profile<br><br> 
    Suggestions, leave a post!


</div>
{% endblock left %} {% block right %}
<div class="col-sm-11" style="
        height:250;
        max-height:500px;
        overflow:auto;
        margin-bottom:10px;
        box-shadow:3px 3px 2px gray;
        background:#ffffff;
        padding-left:5px;
        padding-top:10px;
        padding-bottom:10px;
        margin-top:10px;
        margin-right:10px;
        border:solid 1px black">
    <divclass="col-sm-12 text-left">
        <h3>FRIENDS</h3>
        <ul id="friendList" style="list-style:none">
        </ul>
</div>
</div>
{% endblock right %} {% block content %}

<!-- CREATE POST MODAL -->
<div class="modal fade" id="postModal" tabindex="-1" aria-labelledby="addPostModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="postModalLabel">New Post</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p style="color:red" id='error_message'></p>
                <div class='control-group'>
                    <div class='controls'>
                        <textarea name='content' cols='40' rows='3' class='textarea' required='' id='id_content' placeholder="What's new?"></textarea>
                    </div>
                </div>
                <label class='control-label imagePreview' for="id_image" style="cursor: pointer;" id="imagePreview">
                    <div id='div_id_image' class='control-group'>
                        <div class='controls'>
                            Upload an image
                                <input type='file' name='image' style="display:none" accept='image/*' class='clearablefileinput' id='id_image'>
                                <img src="" alt="Image Preview" class='imagePreviewImage'>
                                
                        </div>
                        
                        <span class="imagePreviewDefaultText"></span>
                    </div>
                </label>
                <div id='removeImage' style="cursor: pointer;" class='removeImage'>X</div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="post_cancel" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="post_save">Save Post</button>
            </div>
        </div>
    </div>
</div>

<!-- EDIT POST MODAL -->
<div class="modal fade" id="editPostModal" tabindex="-1" aria-labelledby="editPostModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editPostModalLabel">Edit Post</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p style="color:red" id='error_message'></p>
                <div class='control-group'>
                    <div class='controls'>
                        <textarea name='content' cols='40' rows='3' class='textarea' required='' id='edit_content' placeholder="What's new?"></textarea>
                    </div>
                </div>
                <label class='control-label imagePreview' for="edit_image" style="cursor: pointer;" id="editImagePreview">
                    <div id='edit_div_id_image' class='control-group'>
                        <div class='controls'>
                            Upload an image
                                <input type='file' name='image' style="display:none" accept='image/*' class='clearablefileinput' id='edit_image'>
                                <img src="" alt="Image Preview" id='editPreviewImage' class='imagePreviewImage'>
                                
                        </div>
                        <span class="imagePreviewDefaultText"></span>
                    </div>
                </label>
                <div id='editRemoveImage' style="cursor: pointer;" class='removeImage'>X</div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="deletePostButton">DELETE POST</button>
                <button type="button" class="btn btn-danger" id="editPost_cancel" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="editPost_save">Save Post</button>
            </div>
        </div>
    </div>
</div>

<div class="text-start" id='posts-box'></div>

<script>
    // NEW POST IMAGE CONTROL
    const inputFile = document.getElementById('id_image')
    const previewContainer = document.getElementById('imagePreview')
    const previewImage = previewContainer.querySelector('.imagePreviewImage')
    const imagePreviewDefaultText = previewContainer.querySelector('.imagePreviewDefaultText')
    const removeImage = document.getElementById('removeImage')

    inputFile.addEventListener("change", function() {
        const file = this.files[0]
        if (file) {
            const reader = new FileReader();
            imagePreviewDefaultText.style.display = 'none';
            previewImage.style.display = 'block';

            reader.addEventListener("load", function () {
                previewImage.setAttribute('src', this.result);
                removeImage.style.display = 'block'
                removeImage.addEventListener('click', function() {
                    inputFile.value = ''
                    previewImage.src = ''
                    previewImage.style.display = 'none'    
                    removeImage.style.display = 'none'                

                    console.log("REMOVE IMAGE")
                })
            });            
            reader.readAsDataURL(file);

        }
        else {
            console.log("NO FILE CHOSEN")
            previewImage.src = ''
            previewImage.style.display = 'none'
        }
        console.log(file)
    })
    
    // EDIT POST IMAGE CONTROL
    const editInputFile = document.getElementById('edit_image')
    const editPreviewContainer = document.getElementById('editImagePreview')
    const editRemoveImage = document.getElementById('editRemoveImage')
    const editPreviewImage = document.getElementById('editPreviewImage')

    editInputFile.addEventListener("change", function() {
        const editFile = this.files[0]
        if (editFile) {
            const editReader = new FileReader();
            editPreviewImage.style.display = 'block';

            editReader.addEventListener("load", function () {
                editPreviewImage.setAttribute('src', this.result);
                editRemoveImage.style.display = 'block'
                editRemoveImage.addEventListener('click', function() {
                    editInputFile.value = ''
                    editPreviewImage.src = ''
                    editPreviewImage.style.display = 'none'    
                    editRemoveImage.style.display = 'none'                

                    console.log("REMOVE IMAGE")
                })
            });            
            editReader.readAsDataURL(editFile);

        }
        else {
            console.log("NO FILE CHOSEN")
            editPreviewImage.src = ''
            editPreviewImage.style.display = 'none'
        }
        console.log(editFile)
    })

    function removeNode(node) {
        var nodeToRemove = document.getElementById(node);
        nodeToRemove.remove();
    }

    function autoheight(x) {
        x.style.height = "5px";
        x.style.height = (15 + x.scrollHeight) + "px";
    }
</script>
{% endblock content %}